# Generated by Django 5.1.1 on 2025-01-05 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventColor',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da cor')),
                ('foreground', models.CharField(max_length=9, verbose_name='Cor do texto')),
                ('background', models.CharField(max_length=9, verbose_name='Cor de fundo')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('start_point', models.DateTimeField(verbose_name='Início do evento (UTC)')),
                ('end_point', models.DateTimeField(verbose_name='Fim do evento (UTC)')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='Fuso horário do evento')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('event_color', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='homepage.eventcolor', verbose_name='Cor do evento')),
            ],
        ),
    ]
