# Generated by Django 5.1.1 on 2025-01-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcolor',
            name='foreground',
        ),
    ]
